parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.json'

plugins:
  - '@typescript-eslint'
  - prettier
  - drizzle

extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:drizzle/recommended'

rules:
  prettier/prettier: 'error'
