x-defaults: &defaults
  env_file: ./.env
  restart: always
  networks:
    - unaplauso-network

x-build-defaults: &build-defaults
  context: .

x-service-defaults: &service-defaults
  <<: *defaults
  build:
    <<: *build-defaults
  depends_on:
    - gateway

services:
  db:
    <<: *defaults
    image: postgres:alpine
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']

  redis:
    <<: *defaults
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '${REDIS_PASSWORD}', '--raw', 'incr', 'ping']

  audit:
    <<: *service-defaults
    build:
      <<: *build-defaults
      target: audit

  auth:
    <<: *service-defaults
    build:
      <<: *build-defaults
      target: auth
    ports:
      - '${AUTH_PORT}:${AUTH_PORT}'

  event:
    <<: *service-defaults
    build:
      <<: *build-defaults
      target: event

  file:
    <<: *service-defaults
    build:
      <<: *build-defaults
      target: file

  gateway:
    <<: *defaults
    build:
      <<: *build-defaults
      target: gateway
    ports:
      - '${GATEWAY_PORT}:${GATEWAY_PORT}'
    depends_on:
      - db
      - redis

  open:
    <<: *service-defaults
    build:
      <<: *build-defaults
      target: open

  payment:
    <<: *service-defaults
    build:
      <<: *build-defaults
      target: payment

networks:
  unaplauso-network:
