@reason = {{$pick reason $value:"spam","fraud","tos_disrespect","stolen_content",null}}
@reportedId = {{$input reportedId $value:1}}
@message = {{$input message $value:null}}
POST {{URL}}/report 
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "reason": {{reason}},
  "reportedId": {{reportedId}},
  "message": {{message}}
}

###

GET {{URL}}/report

###

@userId = {{$input userId $value:1}}
@reportedId = {{$input reportedId $value:1}}
DELETE {{URL}}/report/{{userId}}/{{reportedId}}