/* TODO: Unique init migration + hard-reset */

create extension pg_trgm;

-- POST SCHEMA

-- INSERT INTO topic VALUES
/*
INSERT INTO topic ("name", "aliases") VALUES
('Tecnología', 'tecnologia,tech,innovacion,gadgets,dispositivos,hardware'),
('Salud', 'salud,bienestar,medicina,fitness,nutricion'),
('Educación', 'educacion,aprendizaje,cursos,formacion,conocimiento'),
('Arte', 'arte,pintura,escultura,musica,dibujo'),
('Música', 'musica,conciertos,bandas,instrumentos,melodias'),
('Cine', 'cine,peliculas,documentales,cortometrajes,actores'),
('Literatura', 'literatura,libros,novelas,poesia,cuentos'),
('Videojuegos', 'videojuegos,juegos,gaming,esports,consolas'),
('Deportes', 'deportes,futbol,baloncesto,tenis,natacion'),
('Moda', 'moda,ropa,estilo,tendencias,diseño'),
('Comida', 'comida,gastronomia,recetas,cocina,restaurantes'),
('Viajes', 'viajes,turismo,destinos,aventura,exploracion'),
('Medio Ambiente', 'medio ambiente,ecologia,sostenibilidad,naturaleza,conservacion'),
('Animales', 'animales,mascotas,fauna,flora,conservacion'),
('Ciencia', 'ciencia,investigacion,experimentos,descubrimientos,teoria'),
('Historia', 'historia,eventos,civilizaciones,arqueologia,pasado'),
('Filosofía', 'filosofia,pensamiento,etica,moral,existencia'),
('Psicología', 'psicologia,mente,comportamiento,emociones,terapia'),
('Negocios', 'negocios,emprendimiento,finanzas,marketing,inversion'),
('Marketing', 'marketing,publicidad,redes sociales,estrategia,ventas'),
('Finanzas', 'finanzas,inversiones,ahorro,presupuesto,economia'),
('Emprendimiento', 'emprendimiento,startups,innovacion,creatividad,liderazgo'),
('Software', 'software,programacion,desarrollo,aplicaciones,codigo'),
('Hardware', 'hardware,componentes,electronica,dispositivos,tecnologia'),
('Robótica', 'robotica,robots,automatizacion,ingenieria,inteligencia artificial'),
('Inteligencia Artificial', 'inteligencia artificial,ia,machine learning,deep learning,redes neuronales'),
('Realidad Virtual', 'realidad virtual,rv,virtual reality,inmersion,simulacion'),
('Realidad Aumentada', 'realidad aumentada,ra,augmented reality,interaccion,superposicion'),
('Blockchain', 'blockchain,criptomonedas,bitcoin,ethereum,descentralizacion'),
('Ciberseguridad', 'ciberseguridad,seguridad informatica,hacking,proteccion,privacidad'),
('Diseño', 'diseno,grafico,web,ux,ui'),
('Fotografía', 'fotografia,imagenes,camaras,iluminacion,composicion'),
('Animación', 'animacion,dibujos animados,3d,motion graphics,personajes'),
('Arquitectura', 'arquitectura,edificios,diseño urbano,construccion,espacios'),
('Jardinería', 'jardineria,plantas,flores,paisajismo,cultivo'),
('Mascotas', 'mascotas,perros,gatos,animales de compañia,cuidados'),
('Automóviles', 'automoviles,coches,vehiculos,motores,transporte'),
('Motocicletas', 'motocicletas,motos,vehiculos de dos ruedas,velocidad,aventura'),
('Relojes', 'relojes,tiempo,hora,diseño,precision'),
('Joyería', 'joyeria,anillos,collares,pulseras,diamantes'),
('Muebles', 'muebles,decoracion,diseño de interiores,comodidad,estilo'),
('Electrodomésticos', 'electrodomesticos,cocina,lavado,refrigeracion,hogar'),
('Herramientas', 'herramientas,bricolaje,manualidades,reparaciones,construccion'),
('Juguetes', 'juguetes,niños,diversion,aprendizaje,creatividad'),
('Bebés', 'bebes,niños pequeños,cuidado infantil,productos para bebes,maternidad'),
('Libros', 'libros,lectura,novelas,cuentos,conocimiento'),
('Música Clásica', 'musica clasica,orquesta,sinfonia,compositor,instrumentos'),
('Jazz', 'jazz,improvisacion,blues,swing,musica americana'),
('Rock', 'rock,bandas,guitarra,conciertos,musica alternativa'),
('Pop', 'pop,musica popular,canciones,artistas,tendencias'),
('Agricultura', 'agricultura,cultivo,cosecha,granjas,alimentos'),
('Ganadería', 'ganaderia,animales,cría,pastoreo,producción'),
('Pesca', 'pesca,mariscos,océano,barcos,redes'),
('Minería', 'mineria,minerales,extracción,recursos,excavación'),
('Energía', 'energia,renovable,solar,eólica,nuclear'),
('Transporte', 'transporte,logística,envíos,vehículos,rutas'),
('Telecomunicaciones', 'telecomunicaciones,redes,internet,telefonía,comunicación'),
('Biotecnología', 'biotecnologia,genética,medicina,investigación,organismos'),
('Nanotecnología', 'nanotecnologia,materiales,partículas,ingeniería,ciencia'),
('Aeroespacial', 'aeroespacial,aviación,espacio,cohetes,satélites'),
('Defensa', 'defensa,militar,seguridad,armas,estrategia'),
('Justicia', 'justicia,leyes,derecho,tribunales,abogados'),
('Política', 'politica,gobierno,elecciones,partidos,opinión'),
('Religión', 'religion,espiritualidad,creencias,fe,comunidad'),
('Cultura', 'cultura,tradiciones,costumbres,arte,sociedad'),
('Idiomas', 'idiomas,lenguas,traducción,aprendizaje,comunicación'),
('Geografía', 'geografia,mapas,regiones,clima,paisajes'),
('Astronomía', 'astronomia,estrellas,planetas,galaxias,universo'),
('Matemáticas', 'matematicas,números,ecuaciones,cálculo,geometría'),
('Física', 'fisica,energía,materia,fuerzas,leyes'),
('Química', 'quimica,elementos,compuestos,reacciones,laboratorio'),
('Biología', 'biologia,vida,organismos,células,ecosistemas'),
('Medicina', 'medicina,salud,enfermedades,tratamientos,diagnóstico'),
('Farmacia', 'farmacia,medicamentos,drogas,recetas,salud'),
('Odontología', 'odontologia,dientes,encías,salud bucal,tratamientos'),
('Enfermería', 'enfermeria,cuidados,pacientes,hospitales,salud'),
('Fisioterapia', 'fisioterapia,rehabilitación,movimiento,terapia,salud'),
('Nutrición', 'nutricion,alimentos,dietas,salud,bienestar'),
('Psiquiatría', 'psiquiatria,salud mental,trastornos,terapia,emociones'),
('Sociología', 'sociologia,sociedad,comportamiento,grupos,cultura'),
('Antropología', 'antropologia,humanidad,culturas,orígenes,evolución'),
('Arqueología', 'arqueologia,pasado,civilizaciones,excavaciones,artefactos'),
('Lingüística', 'linguistica,lenguaje,gramática,fonética,semántica'),
('Semiótica', 'semiotica,signos,símbolos,interpretación,comunicación'),
('Ética', 'etica,moral,valores,principios,conducta'),
('Derechos Humanos', 'derechos humanos,libertad,igualdad,justicia,dignidad'),
('Paz', 'paz,armonía,cooperación,entendimiento,resolución'),
('Desarrollo Sostenible', 'desarrollo sostenible,ecología,economía,sociedad,futuro'),
('Ayuda Humanitaria', 'ayuda humanitaria,emergencias,desastres,refugiados,asistencia'),
('Voluntariado', 'voluntariado,servicio,comunidad,ayuda,compromiso'),
('Filantropía', 'filantropia,donaciones,caridad,apoyo,causas'),
('Innovación Social', 'innovacion social,soluciones,impacto,comunidad,cambio'),
('Economía Social', 'economia social,cooperativas,empresas sociales,comunidad,desarrollo'),
('Comercio Justo', 'comercio justo,precios justos,productores,consumidores,ética'),
('Consumo Responsable', 'consumo responsable,ética,sostenibilidad,impacto,elecciones'),
('Alimentación Saludable', 'alimentacion saludable,nutrición,bienestar,ingredientes,recetas'),
('Fitness', 'fitness,deporte,ejercicio,fisico,salud,actividad,gym,gymbro'),
('Mindfulness', 'mindfulness,atención plena,meditación,bienestar,conciencia'),
('Yoga', 'yoga,posturas,respiración,meditación,bienestar'),
('Espiritualidad', 'espiritualidad,conexión,propósito,significado,trascendencia');

INSERT INTO "user" (id, email) VALUES(1, 'lukacerrutti2002@gmail.com');
INSERT INTO user_topic (user_id, topic_id) VALUES(1, 1);
INSERT INTO user_topic (user_id, topic_id) VALUES(1, 2);
INSERT INTO user_topic (user_id, topic_id) VALUES(1, 3);
INSERT INTO favorite_creator (user_id, creator_id) VALUES(1, 1);
*/
