name: CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'apps/**'
      - 'libs/**'
      - '.github/workflows/**'
      - 'Dockerfile'
      - 'nest-cli.json'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'tsconfig.json'
      - 'tsconfig.build.json'
      - 'webpack.config.js'

env:
  SSH_HOST: ${{ contains(github.ref, 'main') && secrets.SSH_PRODUCTION_HOST || secrets.SSH_TESTING_HOST }}
  IMAGE_TAG: ${{ contains(github.ref, 'main') && 'stable' || 'latest' }}
  REGISTRY_HOST: 908027417939.dkr.ecr.sa-east-1.amazonaws.com

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: dorny/paths-filter@master
        id: changes
        with:
          filters: |
            any: '!apps/**'
            audit: 'apps/audit/**'
            auth: 'apps/auth/**'
            file: 'apps/file/**'
            gateway: 'apps/gateway/**'
            open: 'apps/open/**'
            event: 'apps/event/**'
            payment: 'apps/payment/**'

      - uses: docker/setup-buildx-action@master

      - uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: audit build & push
        uses: docker/build-push-action@master
        if: steps.changes.outputs.audit == 'true' || steps.changes.outputs.any == 'true'
        with:
          push: true
          tags: ${{ env.REGISTRY_HOST }}/unaplauso/api-audit:${{ env.IMAGE_TAG }}
          target: audit

      - name: auth build & push
        uses: docker/build-push-action@master
        if: steps.changes.outputs.auth == 'true' || steps.changes.outputs.any == 'true'
        with:
          push: true
          tags: ${{ env.REGISTRY_HOST }}/unaplauso/api-auth:${{ env.IMAGE_TAG }}
          target: auth

      - name: file build & push
        uses: docker/build-push-action@master
        if: steps.changes.outputs.file == 'true' || steps.changes.outputs.any == 'true'
        with:
          push: true
          tags: ${{ env.REGISTRY_HOST }}/unaplauso/api-file:${{ env.IMAGE_TAG }}
          target: file

      - name: gateway build & push
        uses: docker/build-push-action@master
        if: steps.changes.outputs.gateway == 'true' || steps.changes.outputs.any == 'true'
        with:
          push: true
          tags: ${{ env.REGISTRY_HOST }}/unaplauso/api-gateway:${{ env.IMAGE_TAG }}
          target: gateway

      - name: open build & push
        uses: docker/build-push-action@master
        if: steps.changes.outputs.open == 'true' || steps.changes.outputs.any == 'true'
        with:
          push: true
          tags: ${{ env.REGISTRY_HOST }}/unaplauso/api-open:${{ env.IMAGE_TAG }}
          target: open

      - name: event build & push
        uses: docker/build-push-action@master
        if: steps.changes.outputs.event == 'true' || steps.changes.outputs.any == 'true'
        with:
          push: true
          tags: ${{ env.REGISTRY_HOST }}/unaplauso/api-event:${{ env.IMAGE_TAG }}
          target: event

      - name: payment build & push
        uses: docker/build-push-action@master
        if: steps.changes.outputs.payment == 'true' || steps.changes.outputs.any == 'true'
        with:
          push: true
          tags: ${{ env.REGISTRY_HOST }}/unaplauso/api-payment:${{ env.IMAGE_TAG }}
          target: payment

      - uses: appleboy/ssh-action@master
        with:
          script: deploy
          command_timeout: '2m'
          username: ec2-user
          host: ${{ env.SSH_HOST }}
          key: ${{ secrets.SSH_ROOT_KEY }}
