name: CICD

on:
  push:
    branches:
      - main
      - develop

env:
  SSH_HOST: ${{ contains(github.ref, 'main') && secrets.SSH_PRODUCTION_HOST || secrets.SSH_TESTING_HOST }}
  DOCKER_TAG: ${{ contains(github.ref, 'main') && 'stable' || 'latest' }}

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: docker/setup-buildx-action@master

      - uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: docker/build-push-action@master
        with:
          push: true
          tags: unaplauso/api-gateway:${{ env.DOCKER_TAG }}
          target: unaplauso-gateway

      - uses: docker/build-push-action@master
        with:
          push: true
          tags: unaplauso/api-auth:${{ env.DOCKER_TAG }}
          target: unaplauso-auth

      - uses: docker/build-push-action@master
        with:
          push: true
          tags: unaplauso/api-audit:${{ env.DOCKER_TAG }}
          target: unaplauso-audit

      - uses: docker/build-push-action@master
        with:
          push: true
          tags: unaplauso/api-file:${{ env.DOCKER_TAG }}
          target: unaplauso-file

      - uses: appleboy/ssh-action@master
        with:
          script: deploy
          command_timeout: '2m'
          username: ec2-user
          host: ${{ env.SSH_HOST }}
          key: ${{ secrets.SSH_ROOT_KEY }}
